### ISSUE TITLE
Called setState on an unmounted component

### ISSUE THREAD

**Issue by muditgoel01** [egorovsa/react-video-seek-slider#1]
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

**Please check the code for the VideoSeekSlider component.**

printWarning @ vendor.min.js:250
warning @ vendor.min.js:274
warnAboutUpdateOnUnmounted @ vendor.min.js:12171
scheduleWorkImpl @ vendor.min.js:13131
scheduleWork @ vendor.min.js:13089
enqueueSetState @ vendor.min.js:8587
Component.setState @ vendor.min.js:569
VideoSeekSlider._this.setSeeking @ vendor.min.js:49283

**Comment by egorovsa** [comment]
Hi. sorry for such a long time. I did not see the issue.. Now it is fixed in v2.0.2
