### ISSUE TITLE
Deprecation Warning: Invalid 'main' in field in 'index.js'

### ISSUE THREAD

**Issue by derreck503** [egorovsa/react-video-seek-slider#12]
Getting a deprecation warning when running this library with the latest 13.0.6 NextJS build & VideoJS 7.20.3.

**Comment by GuyARoss** [comment]
+1 to this issue

**Comment by egorovsa** [comment]
Hello. Thanks for tour message.  I am checking this.!

**Comment by egorovsa** [comment]
Hey guys! I've created a new NextJs  project "next": "13.1.1" and installed video-seek-slider as well
No any deprecation messages were found.
Would you mind to provide me a bit more information or a small project to reproduce this issue?
