### ISSUE TITLE
react-player entegration

### ISSUE THREAD

**Issue by halilguler** [egorovsa/react-video-seek-slider#13]
Hello,
I'm creating a video player in ReactPlayer for using this package. I'm having trouble integrating the Slider properties. When I move the slider with the mouse, the time is displayed as 00:00 and the time does not change while I'm moving the slider. Can you help me with this issue? Thank you.

codesandbox: https://codesandbox.io/s/agitated-bhaskara-wfrmt2?file=/src/App.js

**Comment by egorovsa** [comment]
Hello It's seems it works ok  and time is changing. Did you reach your goals or it's still an issue?
