### ISSUE TITLE
The preview shown on hover is overflowing on the edges

### ISSUE THREAD

**Issue by rhythmbhiwani** [egorovsa/react-video-seek-slider#14]
When we add the hover image, it goes out of screen on both starting and ending. Can we make some ristrictions so that it doesn't overflows
<img width="792" alt="Screenshot 2023-04-30 at 12 33 36 AM" src="https://user-images.githubusercontent.com/47269183/235319973-32d9b770-e3fc-4f92-aa13-7f4330a357f1.png">

**Comment by egorovsa** [comment]
Hello. Quite strange behaviour.  It would be great if you provide us a codesandbox. We would debug it and find an issue,

**Comment by rhythmbhiwani** [comment]
Sure here's a minimal reproduction https://codesandbox.io/p/sandbox/intelligent-aj-q1xjep?file=%2Fnext.config.js

**Comment by egorovsa** [comment]
Thanks a lot. I will let you know as soon as I find out the reason

**Comment by egorovsa** [comment]
Please use limitTimeTooltipBySides={true} property or update into v6.0.4.
There was a mismatch between description and default property. We've just fixed this. 
Thanks for the answers.

**Comment by rhythmbhiwani** [comment]
Thank you for the quick response.
