### ISSUE TITLE
Seek slider does not resize when its container resizes

### ISSUE THREAD

**Issue by aud-tree** [egorovsa/react-video-seek-slider#15]
### Actual Behavior

When the container the seek slider is in is resized because of a re-render, the seek bar doesn't resize until you manually resize the browser window or fire a window resize event.

### Expected Behavior

The seek bar should resize itself when its container changes size

### Codesandbox

https://codesandbox.io/s/admiring-williamson-cvz8fw

**Comment by egorovsa** [comment]
@aud-tree Hi. Thanks for the issue. will be checked asap and fixed.

**Comment by egorovsa** [comment]
@aud-tree Hi again .
Please update it to v6.0.5
Sizes are recalculated into percentage way.
Let me know if it helped and all's good now.

**Comment by egorovsa** [comment]
https://codesandbox.io/s/pedantic-bas-ff2sjw

**Comment by aud-tree** [comment]
Hi @egorovsa, thanks looking into this! It doesn't seem to have been fixed—the seek slider still isn't resizing until the window is resized:


https://github.com/egorovsa/react-video-seek-slider/assets/5962690/236a033d-ec53-4bcc-bfd8-3e128079d0df

**Comment by egorovsa** [comment]
@aud-tree Something tells me that codesandbox  is caching npm packages and even you use 6.0.5 it still uses 6.0.3
Could you please check it somewhere else?

**Comment by aud-tree** [comment]
I tried it in my local development environment, and the issue is still happening.

`package-lock.json` includes

```json
"node_modules/react-video-seek-slider": {
  "version": "6.0.5",
  "resolved": "https://registry.npmjs.org/react-video-seek-slider/-/react-video-seek-slider-6.0.5.tgz",
  "integrity": "sha512-AtaIrtokxt4xDgipIbQpftpJVwCOWaxNyAWTIZ9e145wZ4nm8Y8KJCudhfWHljCh3rzZOpq83P+itnKtQf53jQ==",
  "peerDependencies": {
    "react": ">=16.8.0",
    "react-dom": ">=16.8.0"
  }
},
```
so it's definitely installed correctly.

**Comment by egorovsa** [comment]
Ok . Thanks. I will check it soon and let you know.

**Comment by egorovsa** [comment]
@aud-tree Let's go with v.6.0.6
https://codesandbox.io/s/prod-star-5wnp7c

**Comment by aud-tree** [comment]
Perfect! Thanks so much for the quick fix!
