### ISSUE TITLE
[FEATURE REQUEST] React 19 support

### ISSUE THREAD

**Issue by kms0219kms** [egorovsa/react-video-seek-slider#17]
On React 19, `TypeError: Cannot read properties of undefined (reading 'ReactCurrentOwner')` this unhandled exception thrown because this library doesn't support React 19. Do you have any plan to support React 19?

**Comment by egorovsa** [comment]
Hello ! Thanks to the message. 
Sure .. Will be updated soon ,

**Comment by egorovsa** [comment]
@kms0219kms it's done . 
please have a look at the last version  v.6.0.7

**Comment by kms0219kms** [comment]
@egorovsa Let me see, please allow me for a minute

**Comment by kms0219kms** [comment]
Works perfect. Let me close this issue as resolved. Thanks a lot
