### ISSUE TITLE
trackWidth not getting updated when window resize event is called

### ISSUE THREAD

**Issue by ashutosh-wynk** [egorovsa/react-video-seek-slider#2]
While playing video player, resizing windows sometimes fails to update trackWidth

<img width="1432" alt="screenshot 2019-01-07 at 7 18 22 pm" src="https://user-images.githubusercontent.com/44193978/50771634-2e7d8480-12b1-11e9-81a9-a501dab1be32.png">

offsetWidth is 0 for the class "track".

**Comment by egorovsa** [comment]
HI. thx . will check it soon!

**Comment by egorovsa** [comment]
Can't reproduce..... Could you please describe step by step to reproduce the issue?

**Comment by gyerts** [comment]
I did reproduced, please make real situation with next structure
59:59 ===============O------------------------- 02:00:00
progress bar should be resized (by CSS) after left time will grow from 59:59 to 01:00:00 progress bar should get smaller to 2 char, after this thumbnail will be detached from progress-bar
01:00:00 =============--O----------------------- 02:00:00

**Comment by gyerts** [comment]
I did fix it by making left side timer and right side duration with fixed width
