### ISSUE TITLE
OnChange time returns 0

### ISSUE THREAD

**Issue by Copser** [egorovsa/react-video-seek-slider#7]
Hey @egorovsa,

nice library 😃 , I'm trying to use it as a solution for some custom video controls that I've built for one of my projects.  

I have a small problem with `onChange` when I want to use the slider to seek time or to get the time just by clicking on the slider it returns 0. Here I have replicated the problem in this [sanbox](https://codesandbox.io/s/practical-brook-uig6z?file=/src/App.js). Default video controls are there to help with playing the video.

Cheers.

**Comment by egorovsa** [comment]
@Copser Hello! Thank you for the message. I will check it ASAP and will let u know the result!

**Comment by egorovsa** [comment]
@Copser I've just tried to comprehend why it's going on so I as see that the "max" property you passed into slider.js equals 0. Could you please check, seems like it's a reason. 
Let me know please!

**Comment by egorovsa** [comment]
Seems I've just found an issue. I will keep you posted!

**Comment by Copser** [comment]
hey @egorovsa, yes max value that I'm passing is the `duration` of the [video](https://developers.cloudflare.com/stream/viewing-videos/using-the-player-api) and yes initially it's 0.

**Comment by Copser** [comment]
@egorovsa I see what you mean here, giving it a `max` value fixes the #8 issue. This is not that great but I think I can work with that and find a workaround, but I still see 0 as a value `onChange` event.

**Comment by Copser** [comment]
@egorovsa I see what you mean here, giving it a `max` value fixes the #8 issue. This is not that great but I think I can work with that and find a workaround, but I still see 0 as a value `onChange` event.

**Comment by Copser** [comment]
@egorovsa I see what you mean here, giving it a `max` value fixes the #8 issue. This is not that great but I think I can work with that and find a workaround, but I still see 0 as a value `onChange` event.

**Comment by egorovsa** [comment]
Don't worry. I will find a way to fix this ;)

**Comment by Copser** [comment]
@egorovsa sorry this was not intended, just wanted to let you know 😄

**Comment by egorovsa** [comment]
@Copser the new bug fix have been publish. Could you please check if it works correct now?

**Comment by Copser** [comment]
@egorovsa hey it works perfectly. I have updated the [sandbox](https://codesandbox.io/s/practical-brook-uig6z?file=/src/App.js). Thanks for fixing the issue, much appreciated 👍
