### ISSUE TITLE
Rouge loader values on video loaded

### ISSUE THREAD

**Issue by Copser** [egorovsa/react-video-seek-slider#8]
Hey @egorovsa,

I just wanted to open another issue, here is a [loom](https://www.loom.com/share/7034ac0f263f4cc68abd65dcab1af473) video, not sure how to reproduce this in the sandbox.

Once the page and video load I can see that slider already have some data loaded, not just that the pseudo-element is offset by 100px. Not sure why is this happening, so wanted to ask you do you maybe have any idea why this can happen.

I can config that progress, currentTime, and max values are 0 on-page and video load.

Cheers.

**Comment by egorovsa** [comment]
Got it! Will try to reproduce!

**Comment by Copser** [comment]
Setting 0 value to `max` will make the slider have a rouge value. A workaround is to know your video duration before you set the `max` value.
